-- Run once in the Supabase SQL editor. No real accounts: user_id is an anonymous id generated by the client.

create table if not exists learner_profile (
  user_id      text not null,
  skill        text not null check (skill in ('code', 'logic', 'critical')),
  level        int  not null default 1,
  last_results jsonb not null default '[]'::jsonb,
  primary key (user_id, skill)
);

create table if not exists attempt (
  id           bigint generated always as identity primary key,
  user_id      text not null,
  challenge_id text not null,
  correct      boolean not null,
  hints_used   int not null default 0,
  seconds      int not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists attempt_user_created_idx on attempt (user_id, created_at desc);

-- key = skill + diff + lang + profile summary
create table if not exists challenge_cache (
  key        text primary key,
  challenge  jsonb not null,
  created_at timestamptz not null default now()
);

-- The backend is the only client. Enabling RLS with no policies blocks the anon key entirely.
alter table learner_profile enable row level security;
alter table attempt         enable row level security;
alter table challenge_cache enable row level security;
